[GENERAL]
; version
software_version = 1.0
; main path
path = /root/repo-sync-external/
; location of log
logfiledir = /var/log/repo-sync-external/
; downloads folder
downloads = 
; final location in repository
final_deb_dir = 
; remote sources
; for each source is a section here in this file required!
remote_sources = 
; repo details
; if there's no binary for an architecture leave it empty
last_update = 

[RUSTDESK]
repo_name = rustdesk/rustdesk
packages = rustdesk
version = 1.1.9
architectures = amd64
name_scheme_arm64 = 
name_scheme_amd64 = ?PACKAGE?-?VERSION?.deb
name_scheme_armhf = 

[RUSTDESK-SERVER]
repo_name = rustdesk/rustdesk-server
packages = rustdesk-server-hbbr,rustdesk-server-hbbs
version = 1.1.7-4
architectures = amd64,arm64,armhf
name_scheme_arm64 = ?PACKAGE?_?VERSION?_arm64.deb
name_scheme_amd64 = ?PACKAGE?_?VERSION?_amd64.deb
name_scheme_armhf = ?PACKAGE?_?VERSION?_armhf.deb



